# Config for the right index finger1
[Fingers]
[[motors]]
finger_name="finger5"
motor1.id = 15
motor1.offset = 0.12217304763960307
motor1.invert = false
motor1.model = "SCS0009"
motor2.id = 16
motor2.offset = 0.08726646259971647
motor2.invert = false
motor2.model = "SCS0009"
[[motors]]
finger_name="finger6"
motor1.id = 13
motor1.offset = 0.0
motor1.invert = false
motor1.model = "SCS0009"
motor2.id = 14
motor2.offset = 0.12217304763960307
motor2.invert = false
motor2.model = "SCS0009"
[[motors]]
finger_name="finger7"
motor1.id = 11
motor1.offset = 0.08726646259971647
motor1.invert = false
motor1.model = "SCS0009"
motor2.id = 12
motor2.offset = 0.12217304763960307
motor2.invert = false
motor2.model = "SCS0009"
[[motors]]
finger_name="finger8"
motor1.id = 17
motor1.offset = 0.0
motor1.invert = false
motor1.model = "SCS0009"
motor2.id = 18
motor2.offset = 0.12217304763960307
motor2.invert = false
motor2.model = "SCS0009"
